version: "3.7"

services:
  # Spark Master
  spark-master:
    image: bitnami/spark:2.4.5
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark_net

  # Spark Worker
  spark-worker:
    image: bitnami/spark:2.4.5
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_LOCAL_IP=spark-worker
    scale: 2
    networks:
      - spark_net

  # Jupyter with Spark Integration
  jupyter:
    image: jupyter/all-spark-notebook:latest
    depends_on:
      - spark-master
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8888:8888
      - 4040-4045:4040-4045
    networks:
      - spark_net

networks:
  spark_net:
    driver: bridge
